name: release

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install deps
        run: npm ci --legacy-peer-deps

      - name: Semantic release
        id: semrel
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

  build-tauri:
    needs: release
    # if: needs.release.outputs.new-release-published == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-14
            args: '--target aarch64-apple-darwin --bundles app'
          - platform: macos-latest
            args: '--target x86_64-apple-darwin'
          - platform: ubuntu-22.04
            args: ''
          - platform: windows-latest
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system deps (Linux only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend deps
        run: npm ci

      - name: Отладка перед Tauri build
        run: rustc --version && cargo --version && npm -v && node -v

      - name: Проверка структуры после билда
        run: |
          ls -la ./src-tauri/target/aarch64-apple-darwin/release/bundle/dmg || echo "dmg папки нет"

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        with:
          args: ${{ matrix.args }}
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets to release
        run: gh release upload ${{ env.RELEASE_TAG }} ./src-tauri/target/release/bundle/**/* --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ steps.semantic.outputs.new_release_version }}
